language: python

matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      python: 3.5
    - os: linux
      sudo: false
      dist: trusty
      python: 3.6
    - os: osx
      osx_image: xcode7.3
      language: generic
    - os: osx
      osx_image: xcode8
      language: generic

addons:
  apt:
    packages:
      - clang-6.0
      - libclang-6.0-dev
      - llvm-6.0-tools
      - python-pip
      - cmake
      - libc6-dev
      - scons
      - qt4-qmake
    sources:
      - llvm-toolchain-trusty-6.0
      - ubuntu-toolchain-r-test

before_script:
  - mkdir -p "$HOME/install" "$HOME/build"
  - env

before_install:
  - uname
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      csrutil status || true;
      brew update;
      brew install scons qt;
    fi

install:
  - pip --version
  - pip install --upgrade pip
  - pip install lit pycodestyle

script:
  - cd "$HOME/build"
  - cmake --version
  - cmake "$TRAVIS_BUILD_DIR" -DCMAKE_CXX_COMPILER=clang++-6.0 -DCPACK_GENERATOR="TGZ;DEB"
  - VERBOSE=1 make all
  - VERBOSE=1 make check
  - VERBOSE=1 make package
  - VERBOSE=1 DESTDIR="$HOME/install" make install
  - if [ "$TRAVIS_SUDO" == "true" ]; then
      sudo make install;
      (cd "$TRAVIS_BUILD_DIR"; git clean -fdx;);
      lit -v "$TRAVIS_BUILD_DIR/test";
    fi

branches:
  except:
    - experimental
