language: python

matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      python: 3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7
    - os: linux
      sudo: false
      dist: trusty
      python: 3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - libclang-6.0-dev
            - llvm-6.0-tools
      env:
        - CC=clang-6.0
        - CXX=clang++-6.0
    - os: osx
      osx_image: xcode7.3
      language: generic
    - os: osx
      osx_image: xcode8
      language: generic

addons:
  apt:
    packages:
      - python-pip
      - libc6-dev
      - cmake
      - scons
      - qt4-qmake

before_script:
  - mkdir -p "$HOME/install" "$HOME/build"
  - uname
  - env | sort

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      csrutil status || true;
      brew update;
      brew upgrade cmake;
      brew install scons qt;
    fi

install:
  - pip --version
  - pip install --upgrade pip
  - pip install lit pex pycodestyle

script:
  - cd "$HOME/build"
  - cmake --version
  - cmake "$TRAVIS_BUILD_DIR" -DCPACK_GENERATOR="TGZ;DEB"
  - VERBOSE=1 make all
  - VERBOSE=1 make test
  - VERBOSE=1 make package
  - VERBOSE=1 DESTDIR="$HOME/install" make install
  - if [ "$TRAVIS_SUDO" == "true" ]; then
      sudo make install;
      (cd "$TRAVIS_BUILD_DIR"; git clean -fdx;);
      lit -v "$TRAVIS_BUILD_DIR/test";
    fi

branches:
  except:
    - experimental
    - 3.x
