language: python

matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      python: "pypy"
    - os: linux
      sudo: required
      dist: trusty
      python: 2.7
    - os: linux
      sudo: false
      dist: trusty
      python: 3.5
    - os: linux
      sudo: false
      dist: trusty
      python: 3.6
    - os: osx
      osx_image: xcode7.3
      language: generic
    - os: osx
      osx_image: xcode8
      language: generic

addons:
  apt:
    packages:
      - cmake
      - libc6-dev
      - scons
      - qt4-qmake

before_install:
  - uname
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      csrutil status || true;
      brew update;
      brew install scons qt;
    fi

install:
  - pip --version
  - pip install --upgrade pip
  - pip install lit pycodestyle

script:
  - mkdir "$HOME/build"; cd "$HOME/build"
  - cmake "$TRAVIS_BUILD_DIR" -DCPACK_GENERATOR="TGZ"
  - VERBOSE=1 make all
  - VERBOSE=1 make check
  - VERBOSE=1 make package
  - if [ "$TRAVIS_SUDO" == "true" ]; then
      sudo make install;
      (cd "$TRAVIS_BUILD_DIR"; git clean -fdx;);
      lit -v "$TRAVIS_BUILD_DIR/test";
    fi
