language: python

matrix:
  include:
    - os: linux
      sudo: false
      python: 2.7
    - os: linux
      sudo: false
      python: 3.2
    - os: linux
      sudo: false
      python: 3.3
    - os: linux
      sudo: false
      python: 3.4
    - os: linux
      sudo: false
      python: 3.5
    - os: linux
      sudo: false
      python: "pypy"
    - os: linux
      sudo: required
      dist: trusty
      python: 2.7
    - os: osx
      osx_image: xcode6.4
      language: generic

addons:
  apt:
    packages:
      - cmake
      - scons
      - qt4-qmake

before_install:
  - uname
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      csrutil status || true;
      brew update;
      command -v pip || { brew install python coreutils; };
      brew install scons qt;
    fi

install:
  - pip --version
  - pip install pep8

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then csrutil status || true; fi
  - pep8 bear/main.py.in
  - cmake . -DCPACK_GENERATOR="TGZ"
  - VERBOSE=1 make all
  - VERBOSE=1 make check
  - mkdir target_dir
  - DESTDIR=target_dir make install
  - VERBOSE=1 make package
