[package]
name = "BuildEAR"
version = "3.1.0"
authors = ["László Nagy <rizsotto at gmail dot com>"]
license = "GPL-3.0-only"
description = "BuildEAR is a tool that generates a compilation database for clang tooling."
homepage = "https://github.com/rizsotto/Bear"
include = [
    "**/*.rs",
    "Cargo.toml",
]

[[bin]]
name = "intercept"
path = "src/main.rs"

[dependencies]
intercept = { path = "./intercept" }
intercept-wrappers = { path = "./intercept-wrappers" }

env_logger = "0.5.13"
error-chain = "0.12"
log = "0.4"

[dependencies.clap]
version = "~2.32.0"
default-features = false

[workspace]
members = [
    "intercept",
    "intercept-wrappers"
]
